import Head from "next/head";
import Styled from "styled-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Tests>s</Tests>
    </>
  );
}

const Tests = Styled.div`
  font-size:40px;
`;
